# Generated by Django 4.0.4 on 2022-05-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamos',
            new_name='Prestamo',
        ),
    ]
